### ISSUE TITLE
Google Map Support

### ISSUE THREAD

**Issue by theabhishekavi** [fossasia/open-event-attendee-android#1055]
**Describe the feature you'd like**
Instead of typing the place where user want to go out, selecting a place on google map would enhance the quality of the app.

**Screenshots**
![img_20190208_112640](https://user-images.githubusercontent.com/35160400/52461372-bd254000-2b94-11e9-9712-acccc7bd4025.jpg)

**Additional context**
User can select a place either by typing or by selecting a place in google map

**Would you like to work on the issue?**

-  Yes

**Comment by theabhishekavi** [comment]
@iamareebjamal should i work on this?

**Comment by AnEnigmaticBug** [comment]
I agree that simply typing a place's name feels slightly strange. There is no immediate feedback that it is valid. For eg: If someone belongs to a small-ish place, he/she won't know whether entering their place's name will work or not. Or if someone's place's name consists of multiple words, how to separate them, how to capitalize them etc

**Comment by liveHarshit** [comment]
How can you suppose that any user wants to select the exact location for searching events?

**Comment by theabhishekavi** [comment]
@liveHarshit i will not take the exact location, i will extract the city name of the marker where user points his/her location.

**Comment by theabhishekavi** [comment]
as @AnEnigmaticBug  said it feels quite strange in typing a place name. So instead of typing, the city name will be extracted from marker of the google map

**Comment by AnEnigmaticBug** [comment]
I see an issue. There are two cases: when the user wants to give his/her current place and when he/she wants to select a different place. The case where he wants to select his current place is already covered by the "Use my current location feature". That leaves us with just the second case.

The issue is that, it is not intuitive how you select a city. Maps are for selecting precise locations. The user will be confused on where to select the exact location.

IMHO, a good solution will be to fetch the list of cities for which the back-end has data and display them in an `AutoCompleteTextView`. This is the most common way other applications ask for similar data.

**Comment by shiv07tiwari** [comment]
I agree with @AnEnigmaticBug . Can I work on this or someone is already working ?

**Comment by theLimitBreaker** [comment]
@iamareebjamal @nikit19  . After Adding auto place complete . Should we consider this. ?

**Comment by ajax-07** [comment]
i would like to work on it if it is still open
