### ISSUE TITLE
Bug in updating profile's twitter link.

### ISSUE THREAD

**Issue by yuvrock** [fossasia/open-event-attendee-android#2524]
There is some issue with the addition of twitter link in profile.
![20191222_164744](https://user-images.githubusercontent.com/35378149/71364420-2aca3700-25c2-11ea-85de-1c873bbe420b.gif)

**Comment by tronku** [comment]
I'll look into this.

**Comment by dheerajkotwani** [comment]
instead of writing "www.twitter/user_name" try with "https://twitter.com/user_name" and same for facebook and instagram.

<blockquote><img src="//abs.twimg.com/favicons/favicon.ico" width="48" align="right"><div><strong><a href="https://twitter.com/user_name">User_name (@User_name) | Twitter</a></strong></div><div>The latest Tweets from User_name (@User_name): "mmmmmmmmmmm I am sleeping."</div></blockquote>
